---
title: "CaliTreeFrogs"
author: "Sarah Gillespie"
date: "5/18/2019"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r start, message = FALSE, warning = FALSE}
library(RMySQL)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(sf)
library(leaflet)
library(lwgeom)
library(lubridate)
library(rtweet)
library(RColorBrewer)
library(ggthemes)
library(harrypotter)
```

## Baja California Treefrogs from iNaturalist

All code, no writing and analysis right now.

National Parks Service about this frog:
https://www.nps.gov/chis/learn/nature/baja-california-treefrog.htm

```{r WranglingData, message = FALSE, warning = FALSE}

#This tutorial explains how to get a CSV of iNaturalist data: https://towardsdatascience.com/citizen-data-science-4d412827bda6

CaliTreeFrogiNat <- read_csv(file = "CaliTreeFrogiNat.csv")

CTFSimp <- CaliTreeFrogiNat %>%
  mutate(year = year(observed_on)) %>%
  mutate(month = month(observed_on)) %>%
  mutate(day = day(observed_on)) %>%
  select(id, user_id, place_guess, latitude, longitude, year, month, day) %>%
  filter(year != "2019")

CTFSum <- CTFSimp %>%
  select(id, month) %>%
  mutate(sighting = 1)
```
```{r FrogsPlot, message=FALSE, warning=FALSE}

ggplot(data=CTFSum, aes(x=month(month, label=TRUE, abbr=TRUE), fill =..count..)) +
  geom_histogram(stat="count") +
  scale_fill_hp(house = "sprout") +
  labs(title = "Baja California Treefrogs", subtitle = "(Pseudacris hypochondriaca)", x = " ", y = "Sightings", caption = "Source: iNaturalist's citizen science data up to Dec 2018. Graphic by @SarahGi522") +
  theme_bw()

#I used the Harry Potter color scheme for this graph.
#I got rid of the x-axis description by adding a space instead of words. The Jan to Dec is self-explanatory.
#this specifically exclues 2019 data becuase we're in the middle of this rainy and frog breeding season and the large amount of data rolling in would make it seem like the frogs are disproportionately active during Jan to Apr but soon we will have more data because the rest of the year hasn't happened yet.

```

## Locations Baja California Treefrogs have been seen

```{r Frogs2018Map, message=FALSE, warning=FALSE}
frog_icon <- icons(iconUrl = "frog_icon.png", 20, 20)

CTF2018Map <- CTFSimp %>%
  filter(year == "2018")

leaflet(CTF2018Map) %>%
  addTiles() %>%
  addMarkers(
    ~CTF2018Map$longitude, ~CTF2018Map$latitude,
    icon = frog_icon,
    label = 'Baja California Treefrog seen here'
    )

#Frog icon is from <a href="http://www.onlinewebfonts.com/icon">Icon Fonts</a> is licensed by CC BY 3.0

```
